### PR TITLE
Fix view.eachDescendant not a function error in TNS rc

### PR DESCRIPTION
**Pull request by mohammadrafigh**

### CODE REVIEW

**Comment by NathanaelA** [comment]
This seems strange, View descends from ViewBase, so it should always have `eachDescendant` 
image

Can you tell me what error you saw?

**Comment by mohammadrafigh** [comment]
> This seems strange, View descends from ViewBase, so it should always have `eachDescendant`
> image
> 
> Can you tell me what error you saw?

Yes it seems weird to me too. But maybe you can try it using `"@nativescript/core": "rc"` which is going to be used with `"@nativescript/angular": "~10.0.0"`. I get `eachDescendant` is not a function.

**Comment by alexander-mai** [comment]
I have the same problem and the fix solves the problem for me.

**Comment by NathanaelA** [comment]
Yep, I was able to confirm that something in RC was a breaking change.

**Pull request merged**
